apiVersion: v1
kind: Service
metadata:
    name: "akslab01-03ac"
    labels:
        app: "akslab01-03ac"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "akslab01-03ac"